apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
          ports:
            - containerPort: 9200
              name: db
              protocol: TCP
            - containerPort: 9300
              name: transport
              protocol: TCP
          env:
           - name: ES_JAVA_OPTS
             value: '-Xmx2g -Xms1g'
          volumeMounts:
            - name: elasticsearch-logging
              mountPath: /data
      volumes:
        - name: elasticsearch-logging
          emptyDir: {}
   
  
       #   volumeMounts:
       #     - name: config-volume
       #       mountPath: /user/share/elasticsearch/config/elasticsearch.yml
     # volumes:
       # - name: config-volume
      #    configMap:
      #      name: elastic-configmap
      #      items:
      #        - key: elastic.yml
       #         path: elastic.yml
