apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-configmap
data:
  elastic.yml: |
    network.host: 0.0.0.0
    discovery.zen.minimum_master_nodes: 1
    discovery.type: single-node
    xpack.security.enabled: false