apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld
        image: mohsendoc/hello-grpc
        imagePullPolicy: Always
        env:
           - name: HELLOWORLD_PORT
             value: "5050"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: helloworld 
  type: ClusterIP  
  ports:
  - port: 80
    targetPort: 5050
    protocol: TCP  


     
