apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: mohsendoc/user-grpc
        imagePullPolicy: Always
        env:
           - name: USER_PORT
             value: "7070"
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user  
  type: ClusterIP  
  ports:
  - port: 80
    targetPort: 7070
    protocol: TCP  